services:
  db:
    image: mysql:8.0
    container_name: manage_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: manage_system
    ports:
      - "3307:3306"
      - "33070:33060"
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/init.sql
